#!/bin/bash
set -e
for x in *; do
  if [[ "$x" =~ ^[0-9]+$ && $(file -b "$x") =~ ^HTML ]]; then
    rm "$x";
  fi
done
mkdir -p .binder
for x in apt.txt environment.yml postBuild; do
  if [[ -f "$x" ]]; then
    mv -f "$x" .binder/
  fi
done
